### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by sudomabider** [alash3al/sqler#14]
Thanks for the great package!

I'll just ask the obligatory question: any plans to support gRPC?

**Comment by alash3al** [comment]
I have a plan for it,  but for now I added redis protocol server,  so you can use it using any redis protocol,  could you tell me you use case exactly?

**Comment by alash3al** [comment]
There are some features,  will work only with rest api,  like authorization, do you have any opinion regarding that?

**Comment by sudomabider** [comment]
I was specifically thinking about communication between microservices which this package is perfect for. But I don't have a strong use case for it at the moment.

Hmmm not sure what's the best way to handle authorization in this case. But I'm happy knowing you have a plan for it :)

Feel free to close.

**Comment by gedw99** [comment]
I also am interesting is using with Protobufs

Use case is for forward engineering efficiency. 
A JS scripting system like sqler is awesome because when you have a ton of types and you just want to add some workflow and validation on top. its very flexible and allows non golang devs to augment the system. But you really want a system to more easily control the types.

For example OpenAPi --> Protobuf and back again code gen.
https://github.com/googleapis/gnostic

So developer story is now:
- developer defines their types in grpc
- gen the golang and openapi code.
- gen the DB CRU code
- js is written against this by non dev.
