### ISSUE TITLE
Where to put sqlconnection string and driver ?

### ISSUE THREAD

**Issue by revskill10** [alash3al/sqler#4]
In the documentation , there's no place to specify driver and sql connection string.
Or am i missing something here ?
Thanks you very much.

**Comment by alash3al** [comment]
Sorry for that, 

Just run the binary you downloaded with the flag -h,  it will display the help for you,  one of them is -dsn it is the connection string,  also there is -engine to specify the driver you want,  I write that in readme now

Sorry again

**Comment by alash3al** [comment]
You can now see the [usage section](https://github.com/alash3al/sqler#usage)

**Comment by alash3al** [comment]
There was a duplicated description for both, it is now fixed in the README too,

`rest` = RESTful server listening address 
`resp` = REDIS server listening address, this is because `SQLer` creates a redis server for you based on your configurations, so you can call your macros from any redis client easily
